//--------------------------------------------------------------------------------------------------//
//		Activity.h																					//
//																									//
//			 Author: Muhammad Saifullah Khan														//
//		Description: Definition of the sglActivity class. This is an abstract class and and each of	//
//					 its derived classes will represent one screen or activity of the program.		//
//			   Date: Sunday, October 25, 2015.														//
//																									//
//--------------------------------------------------------------------------------------------------//

#pragma once

#include <map>
#include "../io/KeyboardListener.h"
#include "../io/MouseListener.h"

/*
An activity is a single, focused thing that the user can do. Almost all activities interact with the user,
so the sglActivity class takes care of displaying a GLUT window whose GUI is defined in its Display() method.
sglActivity is an abstract class and each of its derived classes must override the Display() method.

There are two other methods almost all subclasses of sglActivity will override:

1) KeyboardEvents(unsigned char&, int&, int&) :: This method processes events generated by keyboard input.
It can be overriden to define how a particular sglActivity responds to keyboard input.

2) MouseEvents(int&, int&, int&, int&) :: This method processes events generated by mouse input. It can be
overriden to define how a particular sglActivity responds to mouse input.
*/
class Activity : public KeyboardListener, public MouseListener
{
public:
	virtual void	Display() = 0;


	/*
	Virtual method, can be overriden if the sglActivity needs to perform background operations. This function
	is auto-called repeatedly, with a specified delay in between each call.
	*/
	virtual	void	TimerGL(int&);


	/*
	Virtual method, can be overriden if the sglActivity needs to perform background operations. This function
	is auto-called repeatedly, with a new call starting as soon as last call finishes.
	*/
	virtual void	IdleGL();


	/*
	Virtual method, can be overriden if the sglActivity needs to perform background operations. This function
	is called when an activity is marked as active.
	*/
	virtual void	onStart();


	/*
	Virtual method, can be overriden if the sglActivity needs to perform background operations. This function
	is called when active activity is changed from this one to some other activity.
	*/
	virtual void	onStop();

	// Virtual destructor
	virtual			~Activity();
};